import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Box from "@mui/material/Box";
import { DrawerComponent } from "@/component/drawer/drawer";
import { QueryProvider } from "@/providers/queryClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const drawerWidth = 200;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          <Box
            component="div"
            sx={{ display: "flex" }}>
            <DrawerComponent />
            <Box
              component="main"
              sx={{
                flexGrow: 1,
                p: 1,
                ml: `${drawerWidth}px`,
                boxSizing: "border-box"
              }}>
              {children}
            </Box>
          </Box>
        </QueryProvider>
      </body>
    </html>
  );
}
